export { default as Dashboard } from '../pages/dashboard/Dashboard'
export { default as Transaction } from '../pages/transaction/Transaction'
export { default as TransactionId } from '../pages/transaction/TransactionId'
export { default as Users } from '../pages/users/Users'
export { default as Userdetails } from '../pages/users/Userdetails'
export { default as Usertransaction } from '../pages/users/Usertransaction'
export { default as Kyc } from '../pages/kyc/Kyc'
export { default as Payout } from '../pages/payout/Payout'
export { default as Team } from '../pages/team/Team'
export { default as Settings } from '../pages/settings/Settings'
export { default as Logout } from '../pages/logout/Logout'

